server:
  port: 8000

secret-key: 4359cc432a042e3e285251e3cac5fdd471f5ffc799a3f8069cfa3583587bf361

spring:
  application:
    name: kbo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: ${DB_URL}
    url: jdbc:mysql://db-n9jld-kr.vpc-pub-cdb.ntruss.com:3306/studydb?serverTimezone=Asia/Seoul
    #    username: ${DB_USERNAME}
    #    password: ${DB_PASSWORD}
    username: study
    password: bitcamp!@#123

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  main:
    allow-circular-references: true

  security:
    oauth2:
      client:
        registration:
          #          google:
          #            client-id: YOUR_GOOGLE_CLIENT_ID
          #            client-secret: YOUR_GOOGLE_CLIENT_SECRET
          #            scope: profile, email
          #            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
          #            client-name: Google
          kakao:
            client-name: kakao
            client-id: 6ce6517c567f17b65e53fe4af7b78860
            client-secret: pHTaAAtLNUSo1NPlML5xV40FpCA9Vd4k
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8000/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image
              - account_email
          naver:
            client-name: naver
            client-id: m7BS6vQENr3z2505BGS7  # 앱키 -> REST API 키
            client-secret: I4C_Qg10fI # 네이버 로그인 -> 보안 -> Client Secret 코드
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8000/login/oauth2/code/naver" # yml 파일에서 {} 가 spring 특수문자로 인식되게 하기 위해 " " 사용
            scope:
              - name
              - email
              - profile_image
        provider:
          #          google:
          #            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=consent&access_type=offline
          #            token_uri: https://oauth2.googleapis.com/token
          #            user-info-uri: https://www.googleapis.com/oauth2/v2/userinf
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # "인가 코드 받기" 항목
            token-uri: https://nid.naver.com/oauth2.0/token # "토큰 받기" 항목
            user-info-uri: https://openapi.naver.com/v1/nid/me # "사용자 정보 가져오기" 항목
            user-name-attribute: response # 식별자 . 카카오의 경우 "id" 사용

client:
  id: 640KgVYgO1TJu8FCubds
  secret: CqOswkT0jy
